### ISSUE TITLE
Update & Test HDE yarpmanager application

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/human-dynamics-estimation#116]
Following the creation of `HDE` yarpmanager application https://github.com/dic-iit/component_andy/issues/192 we have to update all the yarpmanager applications and test them and see if all the components are launched correctly through yarpmanager.

CC @lrapetti

**Comment by Yeshasvitvs** [comment]
@lrapetti we should test this as early as possible and close this issue. It will help to launch the demos directly using yarpmanager and reduces bus factor.

**Comment by Yeshasvitvs** [comment]
@lrapetti did we do anything for this ?? :sweat_smile: 
If not, we put this task right after setting up HDE ubuntu machine https://github.com/dic-iit/component_andy/issues/332

**Comment by lrapetti** [comment]
> @lrapetti did we do anything for this ?? 😅

No, but @kouroshD did it for the retargeting application (https://github.com/robotology/human-dynamics-estimation/pull/155), indeed it will serve as base for other applications (basically the dynamic estimation part should just be add)

**Comment by Yeshasvitvs** [comment]
@lrapetti Great. So, can we close this issue ?

**Comment by lrapetti** [comment]
> @lrapetti Great. So, can we close this issue ?

No, I think the one for HDE is not done, but shouldn't take much starting from the application created by @kouroshD (he did just the one for retargeting)

**Comment by Yeshasvitvs** [comment]
Dependencies between different modules of yarpmanager application are important to ensure Rviz model visualization, a related issue https://github.com/robotology/human-dynamics-estimation/issues/116 for the retargeting demo yarpmanager application

CC @lrapetti

**Comment by lrapetti** [comment]
Closing via https://github.com/robotology/human-dynamics-estimation/pull/220
