### ISSUE TITLE
Tasks post HDEv2

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/human-dynamics-estimation#118]
Following the previous [issue on post HDEv2 tasks](https://github.com/dic-iit/component_andy/issues/114), in this issue we document the list of things todo following HDEv2. These are not critical components but more of enhancements:

- [ ] Migrate FT sensors to the new Multiple Analog Sensor interface https://github.com/robotology-playground/forcetorque-yarp-devices/issues/9 and https://github.com/dic-iit/component_andy/issues/194#issuecomment-461064560. https://github.com/robotology-playground/wearables/issues/18
- [ ] The new [HDE thrifts](https://github.com/robotology/human-dynamics-estimation/tree/release/HDEv2/msgs/yarp) stream both the joints / links metadata (e.g. list of names) and their related values. In order to optimize the network bandwith, we should consider to send the metadata through RPC instead of streaming. However, as a side effect, reading the raw message directly from the port would have less information.
- [ ] Develop the `HumanDynamicsClient`
- [ ] Develop the `HumanStateClient`
- [ ] Online creation of the model https://github.com/dic-iit/component_andy/issues/172 & https://github.com/robotology/human-dynamics-estimation/issues/117

@lrapetti @claudia-lat @diegoferigo @DanielePucci

**Comment by lrapetti** [comment]
> * Develop the `HumanStateClient`

This was implemented with the `HumanStateWrapper` (https://github.com/robotology/human-dynamics-estimation/tree/master/wrappers/HumanStateWrapper).



> * Develop the `HumanDynamicsClient`

For the time being there is no particular need for this device. Eventually it will be implemented when needed.

> * Migrate FT sensors to the new Multiple Analog Sensor interface

Specific issue has been opened for this task



> [ ] The new [HDE thrifts](https://github.com/robotology/human-dynamics-estimation/tree/release/HDEv2/msgs/yarp) stream both the joints / links metadata (e.g. list of names) and their related values. In order to optimize the network bandwith, we should consider to send the metadata through RPC instead of streaming. However, as a side effect, reading the raw message directly from the port would have less information.

For the time being I think we can remain with the full name streaming.


Said that, I think we can close  this issue.
