### ISSUE TITLE
Switch to use core homebrew ipopt formula instead of dartsim's one

### ISSUE THREAD

**Issue by traversaro** [robotology/human-dynamics-estimation#131]
See https://github.com/dartsim/homebrew-dart/issues/76 .

**Comment by lrapetti** [comment]
We already switch in the `devel` branch (see https://github.com/robotology/human-dynamics-estimation/pull/128). It will be merged soon to `master`.

**Comment by DanielePucci** [comment]
It is fixed on `devel` branch. Let's close it!
