### ISSUE TITLE
Remove duplicate call to extractJointTorquesFromDynamicVariables in HumanDynamicsEstimator run

### ISSUE THREAD

**Issue by traversaro** [robotology/human-dynamics-estimation#141]
In `HumanDynamicsEstimator::run` method https://github.com/robotology/human-dynamics-estimation/blob/e68a6ab7f5387c3efcdcde7728ae1f843f637a66/devices/HumanDynamicsEstimator/HumanDynamicsEstimator.cpp#L1175 , there seems to be the following code block that is duplicated: 
~~~cxx
pImpl->berdyData.helper.extractJointTorquesFromDynamicVariables(estimatedDynamicVariables,
                                                                    pImpl->berdyData.state.jointsPosition,
                                                                    pImpl->berdyData.estimates.jointTorqueEstimates);
~~~

**Comment by Yeshasvitvs** [comment]
@traversaro Thanks for pointing out.
Fixed in https://github.com/robotology/human-dynamics-estimation/commit/f91920f02978191e5220715226987f05d81c5c8b
