### ISSUE TITLE
Remove base position offset in human-dynamic-estimation

### ISSUE THREAD

**Issue by lrapetti** [robotology/human-dynamics-estimation#152]
The idea is to add rpc functionality to the human-state-provider in order to be able to remove an offset for the base position. In this way it would be possible to take care of the relative transform between two humans.

Given some deadline requirements, this feature will be first implemented on top of the following feature branch: [`feature/visualize-berdy-estimated-wrench`](https://github.com/robotology/human-dynamics-estimation/tree/feature/visualize-berdy-estimated-wrench)

**Comment by lrapetti** [comment]
CC @prashanthr05 @Yeshasvitvs @kouroshD

**Comment by lrapetti** [comment]
It has been implemented in https://github.com/lrapetti/human-dynamics-estimation/commit/08b75c27b718e2ab632b482146188a26ff36ec28.

It allows to remove the position offset for one or more axis, and the rotation offset for one or more axis. Preliminary test have been completed, further testing will follow,

**Comment by lrapetti** [comment]
PR opened to the feature branch (https://github.com/robotology/human-dynamics-estimation/pull/153)

**Comment by claudia-lat** [comment]
In the meanwhile I'm moving this issue onto the Iteration.

**Comment by lrapetti** [comment]
PR has been merged, closing.
