### ISSUE TITLE
Add a wiki page on How to Run HDE Demo

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/human-dynamics-estimation#170]
Following the issue on adding a [wiki page](https://github.com/dic-iit/component_andy/issues/155) for the usage of HDE, one missing point is the wiki page on how to run HDE demo. This issue will track the details on adding a new wiki page that will provide details to run HDE demo. A reference of that new wiki page should be added to https://github.com/robotology/human-dynamics-estimation/wiki/Human-Dynamics-Estimation-Setup-and-Usage

@lrapetti @kouroshD @claudia-lat @DanielePucci

**Comment by Yeshasvitvs** [comment]
A [new wiki page](https://github.com/robotology/human-dynamics-estimation/wiki/Running-HDE-Related-Demos) for running HDE related demos is added.

@lrapetti @kouroshD please double check and feel free to update it if you come across some inconsistencies. Thanks

**Comment by Yeshasvitvs** [comment]
@claudia-lat I moved this issue to review and thought to close it in the next iteration meeting.
Given the change in organization, i think we can close this issue. Let me know.

**Comment by DanielePucci** [comment]
Agreed @Yeshasvitvs
