### ISSUE TITLE
Add CHANGELOG to the repo

### ISSUE THREAD

**Issue by lrapetti** [robotology/human-dynamics-estimation#173]
In order to properly structure the releases of the code contained in this repo, it would be nice to add a `CHANGELOG.md` file tracking the changes among the different release and patches like what is done in other repositories inside `robotology` framework.

**Comment by lrapetti** [comment]
Moving this issue back in Backlog in order to give more visibility. 

It would be better to introduce a Changelog before doing new releases

**Comment by RiccardoGrieco** [comment]
PR #320 introduced the CHANGELOG. Closing.
