### ISSUE TITLE
Clarify software to download in the ESD Can docs

### ISSUE THREAD

**Issue by traversaro** [robotology/human-dynamics-estimation#186]
Following the docs in https://github.com/robotology/human-dynamics-estimation/wiki/Set-up-Machine-for-running-HDE#usb-can-2 the instructions say to download the `CAN_SDK_V***` and `can_usb2_win64_***` files, however those files cannot be found in the linked page https://esd.eu/en/products/can-usb2 . 

It would be great to have some more direct links to the required files. 

cc @kouroshD @lrapetti

**Comment by traversaro** [comment]
cc @fiorisi @marcoaccame

**Comment by kouroshD** [comment]
If I am not wrong the user should login in order to download the files. maybe @lrapetti  can elaborate more on that.

**Comment by traversaro** [comment]
Perhaps also @isorrentino can know something about it.

**Comment by isorrentino** [comment]
@traversaro The links that I put in the [WIKI of element_ftSk_Shoes](https://github.com/dic-iit/element_ftSk_Shoes/wiki/How-to-install-ftShoes#install-usb-can-drivers) are:
* USB-CAN mini https://drive.google.com/open?id=1dWAg3u8jlVcYCuPBcv4ZXflj4NkHC_EO
* USB-CAN2 https://drive.google.com/file/d/1_pDrmburFcgtFZhKYgbDvwucj9HntyEm/view?usp=sharing

**Comment by lrapetti** [comment]
> Probably in https://github.com/robotology/human-dynamics-estimation/wiki/Set-up-Machine-for-running-HDE#usb-can-2 you can use the same links.

since `human-dynamics-estimation` is a public repo we can not put the link to the drive. That's why we just put a general description of the required driver.

**Comment by lrapetti** [comment]
> @traversaro The links that I put in the [WIKI of element_ftSk_Shoes](https://github.com/dic-iit/element_ftSk_Shoes/wiki/How-to-install-ftShoes#install-usb-can-drivers) are:
> 
> * USB-CAN mini https://drive.google.com/open?id=1dWAg3u8jlVcYCuPBcv4ZXflj4NkHC_EO
> * USB-CAN2 https://drive.google.com/file/d/1_pDrmburFcgtFZhKYgbDvwucj9HntyEm/view?usp=sharing
> 
> Probably in https://github.com/robotology/human-dynamics-estimation/wiki/Set-up-Machine-for-running-HDE#usb-can-2 you can use the same links.

probably we should also delete the links from this comment

**Comment by traversaro** [comment]
Beside the archive problem, do we have the URL for downloading those files from the ESD  website?

**Comment by traversaro** [comment]
Ok, I think that CAN SDK (that is the only one actually required for compilation) can be downloaded  after registration at  https://esd.eu/en/software-downloads/27425 (linked from https://esd.eu/en/products/can-sdk), but I don't know where the USB-CAN2 and USB-CAN mini driver used by @isorrentino can be downloaded.

**Comment by Yeshasvitvs** [comment]
> Beside the archive problem, do we have the URL for downloading those files from the ESD website?

The last time I did this was in Oct 2018 at Xsens office and even after the registration, the download option was not available. In the end I got the drivers from @claudia-lat

**Comment by traversaro** [comment]
> > Beside the archive problem, do we have the URL for downloading those files from the ESD website?
> 
> The last time I did this was in Oct 2018 at Xsens office and even after the registration, the download option was not available. In the end I got the drivers from @claudia-lat

If the driver is not available from the website and can only be provided directly from ESD, we should mention it in the docs, as otherwise for any user following the docs it will be impossible to "Download the proper drivers from the ESD electronics" as it is currently written in the docs.

**Comment by traversaro** [comment]
So, just to double check: expect from the CAN SDK, the drivers for the ESD CAN boxes are not available from the website, and instead are available from the CD shipped with the boxes? 
@Yeshasvitvs @lrapetti (Tagging you as you are the mantainers)

**Comment by lrapetti** [comment]
> and instead are available from the CD shipped with the boxes?
> @Yeshasvitvs @lrapetti (Tagging you as you are the mantainers)

Honestly I don't know when/how we got them. I have always used the links that @isorrentino was pointing.

**Comment by claudia-lat** [comment]
I can reply to this question.  Few notes:
- The drivers come with the physical ESD-CAN in this form
![IMG_0384](https://user-images.githubusercontent.com/10923418/75266234-56e87b00-57f2-11ea-9a8e-ce1da63dcf85.JPG)

- In the IIT storage `//storage05.icub.iit.local/repository/`some old versions of the drivers are stored.
![Screenshot 2020-02-25 at 17 16 17](https://user-images.githubusercontent.com/10923418/75266445-a3cc5180-57f2-11ea-95d6-b38178c63800.png)

**Comment by traversaro** [comment]
Great, thanks @claudia-lat !

**Comment by lrapetti** [comment]
I was planning to change the wiki with the following

> - Before proceeding, check if you have the availability of the proper drivers from the [ESD electronic](https://esd.eu/en/products/can-usb2) that are shipped with the can-usb2 device. You should have the following two files:

(I can not do it at the moment since github is crashing when trying to change the wiki)

**Comment by traversaro** [comment]
Perfect, thanks @lrapetti !

**Comment by claudia-lat** [comment]
CC @lrapetti

**Comment by lrapetti** [comment]
> I was planning to change the wiki with the following
> 
> > * Before proceeding, check if you have the availability of the proper drivers from the [ESD electronic](https://esd.eu/en/products/can-usb2) that are shipped with the can-usb2 device. You should have the following two files:
> 
> (I can not do it at the moment since github is crashing when trying to change the wiki)

Done. Hope now it is more clear, closing.
