### ISSUE TITLE
Code Cleanup using Codacy Reviews

### ISSUE THREAD

**Issue by yeshasvitirupachuri** [robotology/human-dynamics-estimation#194]
After the branch clean up #101, we still can improve the code base by cleaning up following the quick suggestions from [Codacy automated review](https://app.codacy.com/gh/robotology/human-dynamics-estimation/issues/index?bid=16781005). In this issue we will track the details related to improving the code base by cleaning up and fixing small issues. 

At the moment, the major branches are 
- [devel](https://github.com/robotology/human-dynamics-estimation/tree/devel) (master is aligned with it)
- [feature/visualize-berdy-estimated-wrench](https://github.com/robotology/human-dynamics-estimation/tree/feature/visualize-berdy-estimated-wrench)

As the [feature/visualize-berdy-estimated-wrench](https://github.com/robotology/human-dynamics-estimation/tree/feature/visualize-berdy-estimated-wrench) is currently under active development, we need to start with code cleanup on the devel branch first.

@lrapetti @kouroshD @claudia-lat @diegoferigo @DanielePucci

**Comment by lrapetti** [comment]
This issue is deprecated, we can close it.
