### ISSUE TITLE
Cleanup CMake code to install YARP devices

### ISSUE THREAD

**Issue by traversaro** [robotology/human-dynamics-estimation#197]
I noticed that in this repo manually wrote .ini files for all the devices are still installed, while YARP has gained support to automatically generated them (reducing the possibility of errors) in version 3.2.0 : https://github.com/robotology/yarp/blob/2522239984ef3e6c26939fe740001ec08189a8cb/doc/release/v3_2_0.md#build-system .

For this reason, I suggest to remove all the manually written .ini files that describe a device, and use instead the much more convenient and less error prone automatic generation provided by YARP, see robotology/icub-main#586 for an example pull request.

**Comment by Yeshasvitvs** [comment]
CC @lrapetti @kouroshD @claudia-lat @Yeshasvitvs

**Comment by lrapetti** [comment]
Done with https://github.com/robotology/human-dynamics-estimation/pull/198
