### ISSUE TITLE
Remove outputPortName fromIWearRemapper device configuration parameters

### ISSUE THREAD

**Issue by yeshasvitirupachuri** [robotology/human-dynamics-estimation#215]
Following this https://github.com/robotology/wearables/issues/83#issuecomment-708976336, the configuration parameter `outputPortName` of `iwearremapper` device needs to be removed from all the [configuration files](https://github.com/robotology/human-dynamics-estimation/blob/master/conf/xml/Human.xml#L17)

CC @lrapetti @kouroshD @claudia-lat

**Comment by lrapetti** [comment]
Fix by https://github.com/robotology/human-dynamics-estimation/pull/353
