### ISSUE TITLE
Add documentation for calibration procedure

### ISSUE THREAD

**Issue by lrapetti** [robotology/human-dynamics-estimation#239]
In time we add multiple different procedures for secondary calibration of the kinematics data.
Those are now documented in PRs/issues or in the rpc response (https://github.com/robotology/human-dynamics-estimation/blob/6e3ada1169387b3105d01b2cd97b7d1cb7e1f93b/devices/HumanStateProvider/HumanStateProvider.cpp#L318-L329).

It would be more proper to add a documentation in the `README`

**Comment by claudia-lat** [comment]
Any update @lrapetti ? Otherwise we can close it.

**Comment by lrapetti** [comment]
PR opened https://github.com/robotology/human-dynamics-estimation/pull/264

**Comment by lrapetti** [comment]
Done in #264, we can close it
