### ISSUE TITLE
Strange tag name for 2.5.0 release

### ISSUE THREAD

**Issue by traversaro** [robotology/human-dynamics-estimation#304]
Just a nitpick/note: all the other releases tag started with a lowercase `v`:
* https://github.com/robotology/human-dynamics-estimation/releases/tag/v2.3.0
* https://github.com/robotology/human-dynamics-estimation/releases/tag/v2.4.0
* https://github.com/robotology/human-dynamics-estimation/releases/tag/v2.4.1

2.5.0 switched to a capital `V`, not sure if this was intentional:
* https://github.com/robotology/human-dynamics-estimation/releases/tag/V2.5.0

fyi @lrapetti

**Comment by lrapetti** [comment]
I have deleted and created again the release, now it can be found under the tag `v2.5.0` https://github.com/robotology/human-dynamics-estimation/releases/tag/v2.5.0.

Thanks for noticing it @traversaro

**Comment by traversaro** [comment]
Thanks for fixing it
