### ISSUE TITLE
human_wrench_provider returning zeros if not attached to HumanStateProvider

### ISSUE THREAD

**Issue by lrapetti** [robotology/human-dynamics-estimation#318]
After merging https://github.com/robotology/human-dynamics-estimation/pull/309, the human_wrench_provider returns all zero if it is not attached to the HumanStateProvider, without returning any error. We should either make it work even without a HumanStateProvider attached, or return an error in case it is not present.

cc @RiccardoGrieco

**Comment by RiccardoGrieco** [comment]
I will open a PR to address this issue. For the time being, #317 should be a good workaround.

**Comment by lrapetti** [comment]
With https://github.com/robotology/human-dynamics-estimation/pull/347, an error will be returned if no `IHumanState` interface is provided. We can wait for the PR and close it.

**Comment by lrapetti** [comment]
Closed vua https://github.com/robotology/human-dynamics-estimation/pull/347
