### ISSUE TITLE
Compilation failure against YARP master (future YARP 3.8) November 2022

### ISSUE THREAD

**Issue by traversaro** [robotology/human-dynamics-estimation#324]
In YARP 3.3 (released in 2019) the following headers where deprecated (see https://www.yarp.it/latest/v3_3_0.html#autotoc_md512):

| Deprecated Header | Replacement |
|:-----------------:|:------------:|
| `yarp/dev/SerialInterfaces.h` | `yarp/dev/ISerialDevice.h` |
| `yarp/dev/PreciselyTimed.h` | `yarp/dev/IPreciselyTimed.h` |
| `yarp/dev/GenericSensorInterfaces.h` | `yarp/dev/IGenericSensor.h` |
| `yarp/dev/Wrapper.h` | `yarp/dev/IWrapper.h` and/or `yarp/dev/IMultipleWrapper.h` | 

However, the inclusion of the deprecated headers, so probably the deprecation went unnoticed. However, in YARP master branch (future YARP 3.8) the headers were removed, so it would be great to remove the use of this deprecated headers, as it has been detected that this repo is using those headers.

Cross-ref : https://github.com/robotology/robotology-superbuild/issues/1303

**Comment by lrapetti** [comment]
Fixed in https://github.com/robotology/human-dynamics-estimation/pull/327
