### ISSUE TITLE
Remove implementation of both IWrapper and IMultipleWrapper from devices

### ISSUE THREAD

**Issue by RiccardoGrieco** [robotology/human-dynamics-estimation#346]
As per title, this issue is to replicate what we did in #344 as a solution for #342.

Currently the devices listed below implement both the interfaces `IWrapper` and `IMultipleWrapper`, which makes them prone to bugs (see above).

Affected devices:
- [x] [HumanControlBoard](https://github.com/robotology/human-dynamics-estimation/tree/master/devices/HumanControlBoard)
- [x] [HumanDynamicsEstimator](https://github.com/robotology/human-dynamics-estimation/tree/master/devices/HumanDynamicsEstimator)
- [x] [HumanStateProvider](https://github.com/robotology/human-dynamics-estimation/tree/master/devices/HumanStateProvider)
- [x] [HumanWrenchProvider](https://github.com/robotology/human-dynamics-estimation/tree/master/devices/HumanWrenchProvider)
- [x] [RobotPositionController](https://github.com/robotology/human-dynamics-estimation/tree/master/devices/RobotPositionController)

cc @lrapetti

**Comment by RiccardoGrieco** [comment]
Changes were implemented in branch https://github.com/robotology/human-dynamics-estimation/tree/devices-fix_wrapper_interfaces, opened draft PR #347 .

**Comment by lrapetti** [comment]
Closed via https://github.com/robotology/human-dynamics-estimation/pull/347
