### ISSUE TITLE
Change Wrapper/Remapper naming convention to `nws`/`nwc`

### ISSUE THREAD

**Issue by lrapetti** [robotology/human-dynamics-estimation#359]
Some time ago, in `yarp` the naming convention `nws`/`nwc` was defined (see https://github.com/robotology/yarp/discussions/2441). This was never ported in this repo where we have instead `Wrapper` and `Remapper` devices. 
We might think of moving to this naming convention. 

cc @traversaro

**Comment by davidegorbani** [comment]
I opened the branch [`update_nws_nwc_name`](https://github.com/robotology/human-dynamics-estimation/tree/update_nws_nwc_name) to change the naming convention.
