### ISSUE TITLE
IK fails sometimes with 48DoF model

### ISSUE THREAD

**Issue by francesco-romano** [robotology/human-dynamics-estimation#36]
While the inverse kinematics successfully manages to obtain the joint configuration for the full 66 DoF model (i.e. 22 joints of 3 DoF each), when we use the simplified model the IK sometimes fails to obtain a reasonable solution, not only quantitative speaking, but also qualitative speaking, see attached gif

![output](https://cloud.githubusercontent.com/assets/2189180/24321680/cadc4dfa-1152-11e7-8026-c2ec03bc409c.gif)

**Comment by francesco-romano** [comment]
Before checking why the IK obtains this solution, we should check the URDF model (e.g. wrong joint limits, wrong rotation axes)

cc @MartaLorenzini

**Comment by francesco-romano** [comment]
Before losing the dumped data, I attach some frames in which it is possible to experience the problem.
It actually seems an IK problem

[wrongFrames.tar.gz](https://github.com/robotology/human-dynamics-estimation/files/1131706/wrongFrames.tar.gz)

**Comment by francesco-romano** [comment]
To be checked again after #71

**Comment by Yeshasvitvs** [comment]
I guess this issue is not relevant anymore as we are using only 66DoF human models with HDEv2. So, I think we can close this issue.

@claudia-lat @DanielePucci

**Comment by claudia-lat** [comment]
Closed #36
