### ISSUE TITLE
CI failing on Windows

### ISSUE THREAD

**Issue by lrapetti** [robotology/human-dynamics-estimation#369]
See failure at https://github.com/robotology/human-dynamics-estimation/actions/runs/6544107072/job/17769907998

**Comment by lrapetti** [comment]
@davidegorbani @traversaro any suggestion?

**Comment by traversaro** [comment]
Those are conflicts between the conda installed by setup-conda and the one installed inside GitHub Actions. The possible fixes are: 
* Simple: force the use of mambaforge, as done in https://github.com/robotology/robometry/commit/be84ef5d9696cfb9909f45ca15eeea534944c93d
* More complex, but resulting in a faster CI: switch to setup-micromamba, as done in https://github.com/robotology/yarp-device-xsensmt/pull/46/commits/9062fc3ed7cf0bed4d3c20507c95e691a27f03f5

**Comment by lrapetti** [comment]
Thank @traversaro 

> * More complex, but resulting in a faster CI: switch to setup-micromamba, as done in [robotology/yarp-device-xsensmt@9062fc3](https://github.com/robotology/yarp-device-xsensmt/commit/9062fc3ed7cf0bed4d3c20507c95e691a27f03f5)

I have implemented this solution (see https://github.com/robotology/human-dynamics-estimation/pull/370), we can close it.
