### ISSUE TITLE
Create a dataset for testing modules

### ISSUE THREAD

**Issue by francesco-romano** [robotology/human-dynamics-estimation#37]
To test (at least in a qualitative way) the modules, we should create a `yarpdataplayer`-friendly test dataset with the data coming from the experiments done in [MAPest](https://github.com/claudia-lat/MAPest).
These data can be used as input and output check for each single module.

**Comment by claudia-lat** [comment]
I'm going to close this issue because equal to [this one ](https://github.com/loc2/element_human-dynamics-estimation/issues/8).
