### ISSUE TITLE
Release human-dynamics-estimation v3.0.0

### ISSUE THREAD

**Issue by lrapetti** [robotology/human-dynamics-estimation#373]
Since https://github.com/robotology/human-dynamics-estimation/pull/372 and https://github.com/robotology/human-dynamics-estimation/pull/367 will break compatibility with previous configurations and dataset, I think we can consider releasing a `v3.0.0` version of the `human-dynamics-estimation` software. What do you think @traversaro? Should we consider instead maintaining the deprecated devices in https://github.com/robotology/human-dynamics-estimation/pull/367?

- [ ] https://github.com/robotology/human-dynamics-estimation/pull/372
- [ ] https://github.com/robotology/human-dynamics-estimation/pull/367

**Comment by traversaro** [comment]
I agree with a clean new major and breaking compatibility, however @S-Dafarra and @mebbaid may have relevant opinions.

**Comment by mebbaid** [comment]
I agree with a new release. I will tag  @claudia-lat @AntonellaTatarelli @LorenzoFiori in this since they are currently using `hde` for various activities and may prefer to use  `HumanLogger` with original naming convention for the short term before the breaking changes in #372
