### ISSUE TITLE
Post-demo activities

### ISSUE THREAD

**Issue by francesco-romano** [robotology/human-dynamics-estimation#45]
This issues summaries all the activities which should take place after the CoDyCo Y4 demo takes place.
I will put here also issues related to other repositories as they have been uncovered during the development of this project.

**Human-Dynamics-Estimation**
- [ ] make the configuration of priors more scalable. At the current state only the use cases needed by the demo have been implemented.
- [ ] move the ROS topic creation into the sources.
- [ ] rename every context name:  from *dynamic* to *dynamics*.
- [ ] evaluate the possibility of creating a static library for that part of code that is re-used (for the moment on copy-paste modality) in each module.
- [ ] make the RViz code in a more compact structure (and clean eventually useless code/variable).
- [ ] add header file in RViz code (for the moment it exists only .cpp).
- [ ] modify color scale (green - red) in effort visualization through temperature message. 
- [ ] fix inverse kinematics issues with 48 DoF model.  
- [ ] c++ code for generating human model by starting from the template (at this stage we create the model by running the Matlab code).  Note: for the creation of the model are required the measurements of the Xsens (coming from mvnx parser) and the position of the sensors (done by the Matlab function `computeSuitSensorPosition.m`).

**YARP**
- [ ] various IDL issues (see [YARP#1132](https://github.com/robotology/yarp/issues/1132) [YARP#1143](https://github.com/robotology/yarp/issues/1143))
- [ ] yarpdataplayer enhancements (for offline processing) see [YARP#1144](https://github.com/robotology/yarp/issues/1144)
- [ ] New `yarp::dev` interfaces: `IMultipleAnalogSensors` (for `wholebodydynamics` and https://github.com/robotology-playground/forcetorque-yarp-devices) , `IFrameProvider` (for https://github.com/robotology-playground/xsens-mvn) and `IMultipleIMUs` (for https://github.com/robotology-playground/xsens-mvn)

**iDynTree**
- [x] Clear documentation issues (at least in Berdy)
- [ ] static-analyser issues (also found by valgrind memcheck)
- [ ] Berdy enumerations: extend them to support more information and avoid to spread hardcoded information around

**wholebodydynamics YARP device**
- [ ] Add a clean way to publish external force-torque information to ROS (see https://github.com/robotology/codyco-modules/tree/nomerge/wbd_ros)

**Misc**
- [x] Add to [how-to-document-modules](https://github.com/robotology/how-to-document-modules) how to publish doxygen documentation automatically by using Travis.
- [ ] Benchmark state-provider on iCubGenova04 blades vs iCubGenova02 blade

**Comment by claudia-lat** [comment]
Added two issues in Human-Dynamics-Estimation section.

**Comment by claudia-lat** [comment]
Some of these activities have been done.  Others are no longer useful because of the refactoring (see [here](https://github.com/robotology-playground/wearables)).
I'm going to close this issue for now.
Closed #45.
