### ISSUE TITLE
YARP driver for offline replay of mvnx data 

### ISSUE THREAD

**Issue by diegoferigo** [robotology/human-dynamics-estimation#48]
I report below the steps I'm working on in order to accomplish the third bullet point of Issue #15.

- [x] Find an XML library that could potentially be included in YARP with `SAX` and `Schema Validation` support, and a proper license
- [x] Try validating the `mvnx` file with the `schema.xsd` provided by Xsens
- [x] Write a SAX parser for XML (mandatory due to the big size of the `mvnx` file), `DOM` is not efficient in this case
- [x] Parse a `mvnx` file inheriting the new XML class
- [ ] Ship this feature in a YARP driver

**Comment by diegoferigo** [comment]
For what concern XML libraries, the table below reports some choices with their features and drawbacks:

| Library name | Language | Features | License |
| --- | --- | --- | --- |
| Xerces | C++  | DOM, SAX, XML Schema              | Apache 2.0                     |
| POCO | C++   | DOM, SAX, XML Schema              | Boost *                            |
| libxml2 | C      | DOM, SAX                                      | GNU LGPL                     |
| expat   | C      | ~SAX                                               | MIT                                 |
| Qt        | C++  | DOM, SAX, Stream, XML Schema | GPL, LGPL, commercial |

[*] Schema Validation is in the POCO Pro Framework

Considering that Schema Validation is an important for us, even if Qt are bulky they are the only complete choice with a license that could fit our needs.

**Comment by diegoferigo** [comment]
cc @lucaTagliapietra

**Comment by drdanz** [comment]
Just for reference, IIRC when I checked some time ago `libxml2` was supporting "XML Schema Part 2" but "XML Schema Part 1" was still a work in progress, but I have no idea what "Part 1 and 2" mean and if there were progresses recently.

**Comment by diegoferigo** [comment]
The reason why I discarded libxml2 was the C interface. I found way easier using the Qt, the APIs are in the same moment simple and provide a good flexibility while parsing a big xml in Stream mode.

The initial version I developed last summer is hosted at https://github.com/robotology-playground/xsens-mvn/tree/master/mvnxparser, we're in the process of polishing it and, maybe, detach the core (`XMLStreamReader`) as separated project.

**Comment by traversaro** [comment]
Somebody remembers why in the end we did not go for Xerces? There was a specific reason or just a preference  for QtXml ?

**Comment by diegoferigo** [comment]
I remember I explored solutions also for a possible inclusion into YARP, and I might have discarded it due to the license. Since we already use Qt libraries they looked a better solution.

**Comment by Yeshasvitvs** [comment]
@diegoferigo @traversaro is this issue still relevant for HDEv2 ? If not we can close it.

**Comment by traversaro** [comment]
If https://github.com/robotology/human-dynamics-estimation/issues/15 has been solved in the new architecture, then this can be closed.

**Comment by diegoferigo** [comment]
This parser was used to read efficiently big `mvnx` files. Since now we decided to not renew the license of Xsens Studio, we don't need anymore the mvnx parser.

However, the `mvnx` parser is only an implementation of a generic stream-based xml parser, and the generic implementation might be useful for future projects. We can discuss f2f where to store it (right now is still in the deprecated `xsens-mvn` repo).

**Comment by DanielePucci** [comment]
@diegoferigo 
Please write a short recap and, if this is the case as spoken F2F, close the issue

**Comment by DanielePucci** [comment]
CC
@diegoferigo

**Comment by diegoferigo** [comment]
Not much to add to my previous comment. @claudia-lat used the parser to avoid loading GB-sized log files in matlab to extract some information. Now, since we don't have anymore the license to generate `mvnx` files, we can move the base class [`XMLStreamReader`](https://github.com/robotology-playground/xsens-mvn/tree/master/mvnxparser/XMLStreamReader) somewhere else, since it is a generic wrapper of the stream-based parsing implemented in the Qt libraries. This is in preparation of deprecating `xsens-mvn` repo.
