### ISSUE TITLE
human-effort-bridge crashes when rviz opens

### ISSUE THREAD

**Issue by francesco-romano** [robotology/human-dynamics-estimation#56]
This happened just before the codyco year 4 demo and the day before.

**Comment by Yeshasvitvs** [comment]
This issue is not relevant any more in the new architecture of HDEv2. So closing this issue.

@claudia-lat @diegoferigo @DanielePucci

**Comment by traversaro** [comment]
> This issue is not relevant any more in the new architecture of HDEv2. So closing this issue.

Why? `human-effort-bridge` is not used anymore?

**Comment by Yeshasvitvs** [comment]
No, we are using HumanDynamicsPublisher now to send joint torques info as ros temperature messages. In all our tests it did not crash Rviz.
