### ISSUE TITLE
Move to robotology? 

### ISSUE THREAD

**Issue by traversaro** [robotology/human-dynamics-estimation#57]
The repo has proudly fought in the battle, perhaps it is time to move it to `robotology`?

cc @drdanz

**Comment by drdanz** [comment]
@traversaro Just let me know if/when you want to move this repo...

**Comment by traversaro** [comment]
@francesco-romano Who is the mantainer of the repo? We should decide, and then the decision is up to him/her .

**Comment by francesco-romano** [comment]
I think @claudia-lat or @diegoferigo  should maintain the repo

**Comment by diegoferigo** [comment]
Yep, we can do it @claudia-lat

**Comment by claudia-lat** [comment]
For me, this could be the time for moving the repo.

**Comment by drdanz** [comment]
done! Please let me know if you all have the required permissions.

**Comment by francesco-romano** [comment]
@drdanz can you give (maximum) permissions on the repo to @claudia-lat @diegoferigo @traversaro and me?

**Comment by drdanz** [comment]
Done
