### ISSUE TITLE
human-state-estimator depends on xsens-mvn and such dependency is not documented 

### ISSUE THREAD

**Issue by traversaro** [robotology/human-dynamics-estimation#64]
See https://github.com/robotology-playground/human-dynamics-estimation/blob/master/human-state-provider/CMakeLists.txt#L8 . 

cc @lucaTagliapietra

**Comment by francesco-romano** [comment]
This dependency should have been very temporary.
Those YARP interfaces should be integrated in YARP devel

**Comment by lrapetti** [comment]
In [`HDEv2`](https://github.com/robotology/human-dynamics-estimation/tree/release/HDEv2) the dependency from [`xsens-mvn`](https://github.com/robotology-playground/xsens-mvn) is dropped, and it will be replaced by the dependency on [`wearables`](https://github.com/robotology-playground/wearables) (It will require to be properly documented).

**Comment by Yeshasvitvs** [comment]
@traversaro @lrapetti I think we can close this issue as it is not related to HDEv2. We can open a new issue if needed.

**Comment by Yeshasvitvs** [comment]
We are closing this issue.
