### ISSUE TITLE
Update robot ROS wrapper to new robot device names

### ISSUE THREAD

**Issue by francesco-romano** [robotology/human-dynamics-estimation#67]
see https://github.com/robotology/robots-configuration/blob/devel/iCubGenova04/wrappers/motorControl/right_leg-mc_wrapper.xml#L21 vs https://github.com/francesco-romano/robots-configuration/blob/764949bba9316e43d846132e7e4d59414351102d/iCubGenova04/wrappers/motorControl/right_leg-mc_wrapper.xml#L21

**Comment by Yeshasvitvs** [comment]
I am not sure what this is related to. Under the new architecture of HDEv2 we will run [ros wrapper](https://github.com/robotology/robots-configuration/blob/master/iCubGenova04/wrappers/motorControl/icub_ros_wrapper.xml) on the real robot to send `joint_states` information through a [ros topic](https://github.com/robotology/robots-configuration/blob/de8f17bef917272f26fe83d40c68c411b17105b9/iCubGenova04/wrappers/motorControl/icub_ros_wrapper.xml#L38).

So, I will close this issue @francesco-romano @diegoferigo @claudia-lat @DanielePucci
