### ISSUE TITLE
How to compute on-line joint acceleration for the vector of measurements y

### ISSUE THREAD

**Issue by claudia-lat** [robotology/human-dynamics-estimation#70]
The joint accelerations are needed for filling in the vector y of the measurements.
For the time being, y is a vector with the entries equal to 0 apart from the external forces readings (force plates + robot).  It means that the estimation of the vector d depends only on the forces and it doesn't take into account any joint acceleration contribution!
In [ MAPest ](https://github.com/claudia-lat/MAPest/blob/master/Experiments/23links_human/src/IK.m) the joint acceleration was computed by using a Savitzky-Golay filter.  Clearly it is not possible  in the on-line acquisition case.
Suggestions on how to proceed? 
@lucaTagliapietra @francesco-romano  @DanielePucci @traversaro

**Comment by claudia-lat** [comment]
@lucaTagliapietra suggested the state space filter solution:
https://github.com/RealTimeBiomechanics/Filter

**Comment by francesco-romano** [comment]
@claudia-lat this is a quite general discussion that is not totally related to the software implementation.
IMHO, discussions of this kind should be hold in `loc2` elements.

**Comment by DanielePucci** [comment]
@francesco-romano 👍

**Comment by claudia-lat** [comment]
The issue was moved into `loc2/element_berdy`.
