### ISSUE TITLE
Use BerdyMAPSolver class instead of computing MAP internally

### ISSUE THREAD

**Issue by francesco-romano** [robotology/human-dynamics-estimation#72]
iDynTree now offers a MAP solver for the Berdy equations.
We should update the `human-dynamics-estimation` module to use this class instead of implementing it.

**Comment by francesco-romano** [comment]
This issue will solve #35

**Comment by traversaro** [comment]
cc @diegoferigo

**Comment by Yeshasvitvs** [comment]
This task is done and BerdyMAPSolver class is used in the implementation of `HumanDynamicsEstimatior` device of HDEv2. So, we can close this issue.

@diegoferigo @claudia-lat @DanielePucci
