### ISSUE TITLE
Considering the base link of the human in the controller for reactive pHRI

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/human-dynamics-estimation#81]
I am [implementing](https://github.com/Yeshasvitvs/wholeBodyControllers/tree/pHRI_standup/controllers/pHRIStandup) the reactive pHRI control laws of AnDy deliverable D4.1 by extending the current standup experiment. In this case, how should the base pose of the human to be considered? I have two questions in this regard

* If I recall correctly, with the current standup experiment setup the transformation from the robot to the human is a fixed transformation. What are the links considered on the robot and the human (e.g., `root_link` of the robot to `pelvis` of human??)for this fixed transformation? @claudia-lat @lucaTagliapietra @diegoferigo @DanielePucci 

* The human-state-provider module gives the values of `baseOriginWRTGlobal` , `baseOrientationWRTGlobal`, `baseVelocityWRTGlobal` as considered in this [thrift](https://github.com/robotology/human-dynamics-estimation/blob/8da06176f555d6d696664d769bcd05a7155460b9/human-state-provider/thrifts/HumanState.thrift#L37) file. Which human link is considered as the base link in general and in the current standup experiment particularly? @francesco-romano

**Comment by Yeshasvitvs** [comment]
Ping! @DanielePucci @lucaTagliapietra @claudia-lat @francesco-romano

**Comment by Yeshasvitvs** [comment]
Moved to [this](https://github.com/loc2/element_human-dynamics-estimation/issues/9) issue

**Comment by francesco-romano** [comment]
@Yeshasvitvs I can be wrong, but this might be the answer you are looking for: https://github.com/robotology/human-dynamics-estimation/blob/master/human-state-provider/conf/human-state-provider.ini#L4

**Comment by Yeshasvitvs** [comment]
@francesco-romano please check the discussion on the other issue and let me know if you find something wrong

**Comment by francesco-romano** [comment]
@Yeshasvitvs I am sorry, but I do not have access to private repositories.

**Comment by Yeshasvitvs** [comment]
@francesco-romano I am afraid I do not have user privileges to grant access to you. So, I took a snapshot of the conversation. Please have a look and let me know your comments
![andy](https://user-images.githubusercontent.com/6505998/36682797-529a8012-1b1c-11e8-88ba-b5a358f6dbd8.png)

**Comment by francesco-romano** [comment]
Do you need help in some particular part?
Regarding the thrift, an alternative can be to use a port monitor attached on the input port to translate from thrift to simple yarn vector (@traversaro for more info on the subject).
For the world frame, just be careful, that the Xsens frame changes for every calibration of the suit

**Comment by Yeshasvitvs** [comment]
For now I am not using the human base pose and velocity in the controller. It is good to know about the usage of port monitor to get yarp vectors from thrift message. Thank you @francesco-romano I will update on the controller status after testing
