### ISSUE TITLE
yarpdataplayer not streaming all the ports from HDE dump

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/human-dynamics-estimation#83]
The recent data dump from the online HDE with FT shoes online has ports from HDE and FT shoes in different directories. If all of this data dump is played using yarpdataplayer only the HDE ports are streamed but not the FT ports. But if the directories are separated and played in different yarpdataplayers, all the ports are streamed correctly. This problem is observed once and has to be tested more to be sure. After that the issue can be opened in yarp

**Comment by lpenco** [comment]
I have the same problem!
Cannot stream multiple data from a single yarpdataplayer

**Comment by Yeshasvitvs** [comment]
The hde_dumper data we collected last time has the following directories

![hde_dumper_data](https://user-images.githubusercontent.com/6505998/41091513-ffa809b8-6a46-11e8-9776-77853ad7eec7.png)

The HDE directory contains the following subdirectories with each containing `data.log` and `info.log` files for `yarpdataplayer` playback
![hde_data](https://user-images.githubusercontent.com/6505998/41091739-8fa19912-6a47-11e8-8e03-bd261a31e86a.png)

The forces directory has the following subdirectories
![ft1](https://user-images.githubusercontent.com/6505998/41091760-9f73c824-6a47-11e8-8ec2-a0f49da84761.png)
![ft2](https://user-images.githubusercontent.com/6505998/41091767-a335cc00-6a47-11e8-9fcb-3c5838a0fb97.png)

`xsensDriver` directory also has `data.log` and `info.log` but when this directory is opened with yarpdataplayer no ports are opened. **I am not sure what data is recorded here**

Now, when I load the `hde_dumper` whole directory with `yarpdataplayer` only the `HDE` data ports are played back normally

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6505998/41092052-451b0166-6a48-11e8-8cb2-34e7962e1890.gif)

When `HDE` directory is loaded with yarpdataplayer all the ports are played back normally

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/6505998/41092243-c345362e-6a48-11e8-8c84-fb12d30e6ea8.gif)

When `forces` directory is loaded with yarpdataplayer all the ports are opened correctly but one port, 'totalForce' of right shoe is not played back while the `totalForce` of the left shoe is playedback normally.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/6505998/41092180-9bdc82b8-6a48-11e8-9f7a-ade6518920a2.gif)

This behavior is observed with only one data dump and I haven't tested if further with more data. This has to be looked further with future data collection during pHRI @claudia-lat @lucaTagliapietra @diegoferigo @DanielePucci

**Comment by Yeshasvitvs** [comment]
@lpenco Do you still have the problem. If possible please post the data dump details here.

**Comment by Yeshasvitvs** [comment]
I believe this is related to the time synchronization as indicated [here](https://github.com/robotology/yarp/issues/1687#issuecomment-394781017). As this issue is related to HDEv1 data this issue is not relevant anymore. So we can close it.

@claudia-lat @diegoferigo @DanielePucci
