### ISSUE TITLE
Add wiki page on setting up a new machine for HDE demo

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/human-dynamics-estimation#86]
In this issue we will track the details related to the setting up a new machine from scratch to run HDE demo with FTShoes containing the skin soles. Eventually this will be documented in a wiki page.

@lrapetti @InesSorrentino @claudia-lat @DanielePucci

**Comment by Yeshasvitvs** [comment]
@lrapetti Please update this issue and close it if the wiki page is finished

**Comment by lrapetti** [comment]
Documentation can be found at https://github.com/robotology/human-dynamics-estimation/wiki/Set-up-Machine-for-running-HDE.

Closing
