### ISSUE TITLE
Implement HumanControlBoard device to send human data to simulink

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/human-dynamics-estimation#88]
Currently [hde-readonly-controlboard](https://github.com/Yeshasvitvs/human-dynamics-estimation/tree/hde_interface/hde-readonly-controlboard) is not compatible with new HDEv2. In this issue we track the details related to updating it to be compatible with taking joint position, velocity and acceleration data coming from `HumanStateProvider` and joint torque data coming from `HumanDynamicsEstimator` to pass the data to matlab simulink

@lrapetti

**Comment by Yeshasvitvs** [comment]
Not necessarily. The first one was designed as a module to work with modules but subscribing to the output ports streaming joint data in thrift format. Now I want to change it to a device called ‘HumanControlBorad’ that will read joint position, velocity through ‘IHumanState’ interface and the subscribe to joint torques output port from ‘HumanDynamicsWrapper’. Later when we implement ‘HumanDynamicsWrapper’ to expose data through ‘IHumanDynamics’ we can update from the logic of reading joint torques port to reading ‘IHumanDynamics’ interface.

**Comment by diegoferigo** [comment]
If I understood what @Yeshasvitvs meant, the new `HumanControlBoard` will have the support of attaching to `IHumanState` and `IHumanDynamics` interfaces. This means that it will run within the same `yarprobotinterface` process (that means same xml file).

This conforms to the architectural choice of HDE v2. As we discussed for all the HDE v2 devices, as soon as we need network transparency we can develop the pairs wrapper-client for each interface. This would allow to run `HumanControlBoard` on a different process / different machine.

**Comment by Yeshasvitvs** [comment]
[HumanControlBoard](https://github.com/Yeshasvitvs/human-dynamics-estimation/tree/feature/humanstateprovider_multi_thread_ik/devices/HumanControlBoard) is added to devices. I implemented only the core methods to access data in matlab simulink through controlboardremapper. Accordingly, we get joint positions and joint velocities from `IHumanState` interface and joint torques from `IHumanDynamics` interace. Ideally, joint accelerations should also be available through `IHumanDynamics` interface but currently they are not set in `HumanDynamicsEstimator`. So, I am setting them to zero in `HumanControlBoard` device.

On reading `<HumanControlBoard>/stateExt:o` data we can read correctly the joint positions, velocities, accelerations and torques indicated by `[ok]`  at the end of the data. But the other methods display `[fail]` as they are not implemented in `HumanControlBoard` and are not necessary to get human joint data in simulink.

![screenshot from 2019-02-01 16-06-29](https://user-images.githubusercontent.com/6505998/52131461-18a77900-263d-11e9-80db-d7c7a9496f41.png)

This test is done with offline wearable data. I will test this correctly in simulink controller next with both offline and online data next.

**Comment by Yeshasvitvs** [comment]
I added the tests for `HumanControlBoard` device [here](https://github.com/Yeshasvitvs/human-dynamics-estimation/tree/feature/humanstateprovider_multi_thread_ik/devices/HumanControlBoard/tests) and ran the test  [`HumanSimulinkController`](https://github.com/Yeshasvitvs/human-dynamics-estimation/tree/feature/humanstateprovider_multi_thread_ik/devices/HumanControlBoard/tests/HumanSimulinkController) with [offline wearable data](https://github.com/dic-iit/component_andy/tree/master/Wearable_Data/XSensSuit) from xsens suit device.

Accordingly, with the data set of **left knee** movement of 90 degrees, I see the correct joint angles in simulink scope

![screenshot from 2019-02-03 16-47-15](https://user-images.githubusercontent.com/6505998/52179076-0d3b8580-27d6-11e9-937e-cac72fbfd5a7.png)

For the **right knee** movement of 90 degrees, I see the correct joint angles in simulink scope

![screenshot from 2019-02-03 16-50-35](https://user-images.githubusercontent.com/6505998/52179084-26dccd00-27d6-11e9-8d47-271fe844a34d.png)

Also, the joint torques values are read correctly on simulink side from the `HumanControlBoard` device

![screenshot from 2019-02-03 16-48-20](https://user-images.githubusercontent.com/6505998/52179087-3c51f700-27d6-11e9-8aa5-c090e1333a2d.png)

![screenshot from 2019-02-03 16-52-24](https://user-images.githubusercontent.com/6505998/52179090-3fe57e00-27d6-11e9-9985-0818076dc45c.png)

**NOTE:** The joint torque values may not be reasonable with respect to the knee joint angles. This is because the time synchronization differences in the playback of xsens werable data and the ftshoes wearable data.

A final test with online data from suit and shoes with a human subject has to be done before closing this issue. @lrapetti and I will do this test soon and update the issue.

**Comment by Yeshasvitvs** [comment]
During this testing https://github.com/dic-iit/component_andy/issues/193#issuecomment-461117811 @lrapetti and I tested the new `HumanControlBoard` device with the human movements as shown below

- A set of arms to T pose 5 times
- A set of two feet squat 5 times

![ezgif com-video-to-gif 16](https://user-images.githubusercontent.com/6505998/52362750-8559b380-2a41-11e9-9100-1f78d56a421a.gif)

The corresponding **joint angle data in degree** seen in matlab scope is shown below

![screenshot from 2019-02-06 17-57-03](https://user-images.githubusercontent.com/6505998/52362951-fd27de00-2a41-11e9-9e85-f9b51850356c.png)

![screenshot from 2019-02-06 17-57-24](https://user-images.githubusercontent.com/6505998/52362959-0153fb80-2a42-11e9-8d35-bebc78184073.png)

The corresponding **joint torques** seen in matlab scope is shown below

![screenshot from 2019-02-06 17-59-55](https://user-images.githubusercontent.com/6505998/52362994-116bdb00-2a42-11e9-93d1-e130ca61acee.png)

![screenshot from 2019-02-06 18-00-40](https://user-images.githubusercontent.com/6505998/52362999-13ce3500-2a42-11e9-9c44-c91a8ababc7d.png)


So, the simulink controllers gets the human data faithfully from `HumanControlBoard` device.

One key details a new user has to be aware is that in case of feet or knee values and direction being wrong in the matlab scope. The problem could be feet or knee distortion as observed in this case 
https://github.com/dic-iit/component_andy/issues/188#issuecomment-461118542. 

We can close this issue now and when we perform another test of HDEv2 with another [human subject and the corresponding urdf model](https://github.com/robotology-playground/human-gazebo), we can update this issue with the matlab plots from the test.

@DanielePucci @lrapetti
