### ISSUE TITLE
Storing human name-subject number data file

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/human-dynamics-estimation#92]
The [human-models](https://github.com/loc2/component_andy/tree/master/human-models) repository currently contains the subject number and the subject related data. But we cannot store the file indicating **name-subject number** on this public repo due to GDPR. So, we need to decide on a proper way to store this file such that any new user who wants to do experiments with HDEv2 will know the exact subject to consider for the urdf and online experiments. 

@DanielePucci @claudia-lat @lrapetti @kouroshD @traversaro

**Comment by DanielePucci** [comment]
@Yeshasvitvs 
Please keep this management and delicate issue in the private repo of our organisation. Thanks
